version: '3.7'

services:
  nudges:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/usr/src
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    ports:
      - 5432:5432
    expose: 
      - 5432

volumes:
  postgres_data: